### ISSUE TITLE
When parsing raml with traits it throws: Warning: array_replace_recursive(): Argument #1 is not an array

### ISSUE THREAD

**Issue by ronnkriibi** [alecsammon/php-raml-parser#45]
Hi.

I am trying to parse this raml spec [link to Github](https://github.com/scaganoff/example-eventlog-api)
with your parser and it throws an error Warning: array_replace_recursive(): Argument # 1 is not an array in ..\vendor\alecsammon\php-raml-parser\src\Parser.php on line 298.
Here to be more precise: 
``` php
if (isset($newArray[$key])) {
  $newArray[$key] = array_replace_recursive($newArray[$key], $newValue);
} else {
  $newArray[$key] = $newValue;
}
```
I think you should also add: is_array($newArray[$key])

**Comment by alecsammon** [comment]
Hi Roland,

could you try using v1 - it should be fixed :)

**Comment by ronnkriibi** [comment]
Well, I tried to pull the version 1.0.0 with the composer but I am not sure if I pulled the correct one. My composer.json looks something like this 
```javascript
	"repositories": [{
		"type": "vcs",
		"url": "http://github.com/alecsammon/php-raml-parser.git"
	}],
"require-dev": {
		"alecsammon/php-raml-parser": "1.0.*@dev"
}
```
Composer final output was this: Updating alecsammon/php-raml-parser (dev-master 1f145e6 => 1.0.0.x-dev 70c8a73)

So I ran the Parser again with the update package and the warning was not fixed. Besides that, It gave me a bunch of new warnings and one Fatal error :)

**Comment by alecsammon** [comment]
Hi Ronald,

Sorry for the delay - I believe I have now fixed this in 1.0.0. So if you do a composer update it hopefully will work!

In your example there is a issue with the JSON in https://github.com/scaganoff/example-eventlog-api/blob/master/eventListExample.json - you're missing commas between the objects in the array.

**Comment by ronnkriibi** [comment]
It is now fixed, but there is a similar mistake in Paraser.php in function replaceTypes() in line 343.

I knew that there was a problem in the JSON.

**Comment by alecsammon** [comment]
Awesome - thanks :)

Also fixed
